/// Flutter icons CustomAppIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomAppIcon
///      fonts:
///       - asset: fonts/CustomAppIcon.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class CustomAppIcon {
  CustomAppIcon._();

  static const _kFontFam = 'CustomAppIcon';

  static const IconData person_outline = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData award = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData cog = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData flash_outline = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData heart_empty = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData fire = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData chevron_left = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData add = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData moon = const IconData(0xf186, fontFamily: _kFontFam);
  static const IconData firefox = const IconData(0xf269, fontFamily: _kFontFam);
  static const IconData sweden = const IconData(0xf601, fontFamily: _kFontFam);
}
