/// Flutter icons SocialMediaIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SocialMediaIcon
///      fonts:
///       - asset: fonts/SocialMediaIcon.ttf
///
///
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SocialMediaIcon {
  SocialMediaIcon._();

  static const _kFontFam = 'SocialMediaIcon';

  static const IconData facebook =
      const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData twitter = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData github_circled =
      const IconData(0xf09b, fontFamily: _kFontFam);
}
